const fs=require('node:fs'), vm=require('node:vm'), assert=require('node:assert/strict');
const elements=new Map(), calls=[], documentListeners={};
function element(id) {
 if (!elements.has(id)) elements.set(id,{value:'1',checked:true,clientWidth:800,clientHeight:400,width:800,height:400,style:{},classList:{toggle(){}},listeners:{},addEventListener(name,fn){this.listeners[name]=fn},getBoundingClientRect(){return {left:0,top:0,width:800,height:400}},getContext(){return new Proxy({},{get:()=>()=>{}})},replaceChildren(){},append(){},setPointerCapture(){}});
 return elements.get(id);
}
const state={video:{name:'test',width:1920,height:1080,frame_count:5},fps:60,frames:{},suggestions:{'0':[{type:'point',x:100,y:100}],'1':[{type:'point',x:200,y:200}]}};
const context=vm.createContext({console,Math,Number,Object,String,Array,Error,document:{getElementById:element,createElement:()=>element(Math.random()),addEventListener(name,fn){documentListeners[name]=fn},activeElement:{tagName:'BODY'}},window:{},ResizeObserver:class{observe(){}},Image:class{complete=true;naturalWidth=1920;set src(v){queueMicrotask(()=>this.onload())}},fetch:async(route,options)=>{if(!options)return {ok:true,json:async()=>state};const body=JSON.parse(options.body);calls.push(body);return {ok:true,json:async()=>({label:{status:body.status,objects:body.objects}})}},queueMicrotask,confirm:()=>true});
const html=fs.readFileSync('src/video_annotating_interface/static/index.html','utf8');vm.runInContext(html.split('<script>')[1].split('</script>')[0],context);
const tick=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
 await tick();
 assert.equal(vm.runInContext('viewScale*state.video.height<=canvas.height',context),true,'whole frame fits');
 const before=vm.runInContext('coords({clientX:300,clientY:200})',context);
 let prevented=false;element('canvas').listeners.wheel({deltaY:-300,clientX:300,clientY:200,preventDefault(){prevented=true}});
 assert(prevented);const after=vm.runInContext('coords({clientX:300,clientY:200})',context);
 assert(Math.abs(before.x-after.x)<1e-8 && Math.abs(before.y-after.y)<1e-8,'cursor anchor');
 const zoom=vm.runInContext('zoom',context);await vm.runInContext('go(1)',context);await tick();
 assert.equal(calls[0].objects[0].x,100,'unchanged suggestion saved');assert.equal(vm.runInContext('zoom',context),zoom,'zoom retained');
 await vm.runInContext('removeObject(0)',context);await tick();
 assert.equal(calls.at(-1).status,'absent','removal of final suggestion saves absence');
 await vm.runInContext("addObject({type:'point',x:300,y:150})",context);await tick();
 await vm.runInContext('go(2)',context);await tick();
 assert.equal(calls.at(-1).objects.length,1);assert.equal(calls.at(-1).objects[0].x,300,'edited objects replace suggestions');
 await vm.runInContext('go(0)',context);await tick();
 await vm.runInContext("addObject({type:'point',x:105,y:102})",context);await tick();
 assert.equal(calls.at(-1).objects.length,1,'near suggestion replaced');
 await vm.runInContext("addObject({type:'point',x:200,y:100})",context);await tick();
 assert.equal(calls.at(-1).objects.length,2,'separate ball added');
 await vm.runInContext("addObject({type:'point',x:108,y:103})",context);await tick();
 assert.equal(calls.at(-1).objects.length,2,'near human point replaced');
 assert.equal(calls.at(-1).objects[1].x,200,'other ball preserved');
 await vm.runInContext("addObject({type:'box',x:105,y:100,width:10,height:10})",context);await tick();
 assert.equal(calls.at(-1).objects.length,3,'box remains a separate object');
 async function press(code,key) { documentListeners.keydown({code,key,shiftKey:false,preventDefault(){}});await tick();await tick(); }
 await press('KeyD','d');assert.equal(vm.runInContext('frame',context),1);
 await press('KeyA','a');assert.equal(vm.runInContext('frame',context),0);
 element('step').value='2';
 await press('KeyS','s');assert.equal(vm.runInContext('frame',context),2);
 await press('KeyW','w');assert.equal(vm.runInContext('frame',context),0);
 await vm.runInContext('zoomAt(1,400,200)',context);
 await vm.runInContext("addObject({type:'point',x:140,y:103})",context);await tick();
 assert.equal(calls.at(-1).objects.length,3,'near correction replaces at fit scale');
 assert.equal(calls.at(-1).objects[0].x,140);
 await vm.runInContext('zoomAt(12,400,200)',context);
 const screenRadius = vm.runInContext('40/viewScale',context);
 assert(screenRadius < 10,'zoom reduces video-coordinate radius');
 await vm.runInContext("addObject({type:'point',x:172,y:103})",context);await tick();
 assert.equal(calls.at(-1).objects.length,4,'32px separation adds a distinct point at high zoom');
 await vm.runInContext("addObject({type:'point',x:177,y:103})",context);await tick();
 assert.equal(calls.at(-1).objects.length,4,'5px correction replaces at high zoom');
 assert.equal(calls.at(-1).objects[3].x,177);
 console.log('UI behavior checks passed');
})().catch(error=>{console.error(error);process.exitCode=1});
